complexity:
  LongMethod:
    threshold: 120
  NestedBlockDepth:
    threshold: 6
  StringLiteralDuplication:
    active: true
    excludes:
      - '**/*.kts'
      - '**/test/**'
      - '**/*Test.kt'
      - '**/*Spec.kt'
  ComplexInterface:
    active: true
  CyclomaticComplexMethod:
    ignoreSingleWhenExpression: true
  LargeClass:
    excludes:
      - '**/test/**'
      - '**/*.Test.kt'
      - '**/*.Spec.kt'
  MethodOverloading:
    active: true
  TooManyFunctions:
    thresholdInClasses: 15
    excludes:
      - '**/test/**'
      - '**/functionalTest/**'

coroutines:
  GlobalCoroutineUsage:
    active: true

comments:
  CommentOverPrivateProperty:
    active: true
  UndocumentedPublicClass:
    active: true
    excludes:
      - '**/test/**'
      - '**/samples/**'
  UndocumentedPublicFunction:
    active: true
    excludes:
      - '**/test/**'
      - '**/samples/**'

exceptions:
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true
  ThrowingExceptionInMain:
    active: true
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: true
    excludes:
      - '**/test/**'

naming:
  ClassNaming:
    ignoreAnnotated:
      - 'org.junit.jupiter.api.Nested'
  FunctionNaming:
    excludes: []
    ignoreAnnotated:
      - 'Test'
      - 'ParameterizedTest'
      - 'RepeatedTest'
      - 'TestFactory'
      - 'Composable'
      - 'androidx.compose.runtime.Composable'
  TopLevelPropertyNaming:
    constantPattern: '[a-z][_A-Za-z0-9]*|[A-Z][_A-Z0-9]*'
  InvalidPackageDeclaration:
    excludes:
      - '**/build-logic/**/*.kt'
      - '**/*.kts'
  NonBooleanPropertyPrefixedWithIs:
    active: true
  VariableMaxLength:
    active: true
  VariableMinLength:
    active: true

performance:
  SpreadOperator:
    excludes:
      - '**/test/**'
      - '**/functionalTest/**'

potential-bugs:
  DontDowncastCollectionTypes:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  ImplicitUnitReturnType:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true

style:
  ReturnCount:
    max: 4
    excludeGuardClauses: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
      - 'androidx.compose.desktop.ui.tooling.preview.Preview'
  BracesOnIfStatements:
    active: true
    singleLine: 'consistent'
    multiLine: 'consistent'
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ForbiddenComment:
    active: true
    comments:
      - value: 'FIXME:'
        reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
      - value: 'STOPSHIP:'
        reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
      - value: 'TODO:'
        reason: 'Forbidden TODO todo marker in comment, please do the changes.'
      - value: '@author'
        reason: 'Authors are not recorded in KDoc.'
    excludes:
      - '**/detekt-rules-style/**/ForbiddenComment.kt'
  ForbiddenImport:
    active: true
    imports:
      - value: 'org.assertj.core.api.Assertions'
        reason: 'Import Assertions.assertThat instead.'
      - value: 'org.junit.jupiter.api.Assertions*'
        reason: 'Use AssertJ assertions instead.'
      - value: 'org.junit.jupiter.api.assertAll'
        reason: 'Use AssertJ assertSoftly instead.'
      - value: 'org.junit.jupiter.api.assertThrows'
        reason: 'Use AssertJ assertThatCode { }.isInstanceOf() or assertThatExceptionOfType().isThrownBy { } instead.'
      - value: 'org.junit.jupiter.api.assertDoesNotThrow'
        reason: 'Use AssertJ assertThatCode { }.doesNotThrowAnyException() instead.'
      - value: 'java.util.stream.*'
        reason: "Use Kotlin's sequences instead."
      - value: 'org.jetbrains.kotlin.js.*'
        reason: "detekt does not support Kotlin/JS at this time"
      - value: 'org.jetbrains.kotlin.backend.*'
        reason: "detekt interacts with compiler frontend only"
  ForbiddenMethodCall:
    active: true
    methods:
      - 'kotlin.io.print'
      - 'kotlin.io.println'
      - 'java.net.URL.openStream'
      - 'java.lang.Class.getResourceAsStream'
      - 'java.lang.ClassLoader.getResourceAsStream'
      - 'kotlin.system.measureTimeMillis'
  ForbiddenVoid:
    ignoreOverridden: true
  MagicNumber:
    excludes:
      - '**/*.kts'
      - '**/test/**'
      - '**/*Test.kt'
      - '**/*Spec.kt'
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
      - '1000'
  MandatoryBracesLoops:
    active: true
  MaxLineLength:
    excludes:
      - '**/test/**'
      - '**/*Test.kt'
      - '**/*Spec.kt'
    excludeCommentStatements: true
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryInnerClass:
    active: true
    ignoreAnnotated:
      - 'Nested'
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseLet:
    active: true
  VarCouldBeVal:
    ignoreAnnotated:
      - 'Parameter'
  WildcardImport:
    excludeImports: []

empty-blocks:
  EmptyDefaultConstructor:
    excludes:
      - '**/build/**'
